[package]
name = "e172"
description = "UI framework for Rust"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/NazarK0/e172"
homepage = "https://github.com/NazarK0/e172"
keywords = ["ui_framework", "gui", "declarative_gui"]
categories = ["gui"]

[dependencies]
downcast-rs = "2.0.2"
dyn-clone = "1.0.20"
kurbo = "0.13.0"
parley = "0.8.0"
peniko = "0.6.0"
pollster = "0.4.0"
uuid = { version = "1.23.1", features = ["v4"] }
vello = "0.8.0"
wgpu = "28.0.0"
winit = "0.30.13"
